### PR TITLE
Report API errors in generated exceptions

### LINKED ISSUE #345: Add error reporting support
Error format 

```
{..., "response": {"data": {"error": "REPORT THIS STRING" } }, ...}
```

Either via logging or by adding the string to the generated error.

### PR DESCRIPTION
**Pull request by morgen-peschke**
This is best-effort, so downstream should probably not build logic around it. Hopefully this will make logs more useful.

Fixes #345

### CODE REVIEW

File: core/src/main/scala/com/banno/vault/models/VaultApiError.scala [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package com.banno.vault.models
+
+import io.circe.{DecodingFailure, Json}
+import org.http4s.Status
+
+import scala.util.control.NoStackTrace
+
+final case class VaultApiError(status: Status, errors: List[String])
+    extends RuntimeException(errors.mkString("Vault API Errors:\n", "\n", ""))
+    with NoStackTrace
```
Comment (rossabaker) [inline core/src/main/scala/com/banno/vault/models/VaultApiError.scala:10]: Why `NoStackTrace`?  I usually end up regretting this.

Comment (morgen-peschke) [reply core/src/main/scala/com/banno/vault/models/VaultApiError.scala:10]: In this case it should be OK. 

The error is created from input and never thrown on it's own, so the exact place will always be in `VaultApiError.decode`. 

The more relevant stack trace will be the one in `VaultResponseError`, and since `VaultApiError` is only ever used as a cause of `VaultResponseError` we should always have that.

**Review by rossabaker — APPROVED** [review]
